name: Generate Content

on:
  push:
    branches:
      - dev

  workflow_dispatch:

  schedule:
    - cron: '0 */12 * * *'

jobs:
  create-article:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Article
        run: |
          git config --local user.name 'Github Action' 
          git config --local user.email action@github.com
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./scripts/blog-generator.sh
        shell: bash